all:
  hosts:
    master-1:
      ansible_host: 192.168.1.224
      ip: 192.168.1.224
      access_ip: 192.168.1.224
    worker-1:
      ansible_host: 192.168.1.225
      ip: 192.168.1.225
      access_ip: 192.168.1.225
    worker-2:
      ansible_host: 192.168.1.226
      ip: 192.168.1.226
      access_ip: 192.168.1.226
    worker-3:
      ansible_host: 192.168.1.227
      ip: 192.168.1.227
      access_ip: 192.168.1.227
  children:
    kube-master:
      hosts:
        master-1:
    kube-node:
      hosts:
        master-1:
        worker-1:
        worker-2:
        worker-3:
    etcd:
      hosts:
        master-1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
